version: '3.8'

services:
  app:
    image: aakash:1.0
    ports:
      - "8080:8080"  # Expose the container's port 8080 to the host's port 8080
    environment:
      - ENV=staging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
